matrix:
  include:
    language: python
    python:
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    install: 
    script:
    - python FooFinder/test.py
deploy:
    provider: pypi
    username: <username>
    password: <password>
    edge: true # opt in to dpl v2