# Copying from: https://github.com/brandtbucher/travis-python-matrix

matrix:
  include:
    - name: CPython 3.8 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.8

    - name: CPython 3.7 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7

    - name: CPython 3.6 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.6

    - name: CPython 3.5 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.5

    - name: CPython 3.8 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8

    - name: CPython 3.7 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7

    - name: CPython 3.6 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6

    - name: CPython 3.5 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.2

    - name: CPython 3.8 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8 --x86

    - name: CPython 3.7 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7 --x86

    - name: CPython 3.6 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6 --x86

    - name: CPython 3.5 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.2 --x86

    - name: CPython 3.8 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.6 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

    - name: CPython 3.5 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
  
    - name: CPython 3.8-dev on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
    
    - name: CPython 3.8.0 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
    
    - name: CPython 3.7 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.6 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

    - name: CPython 3.8 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.6 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.5 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5
        - pyenv install $PYENV_VERSION
    
    - stage: deployment
      language: python
      os: linux
      dist: xenial
      python: 3.8.1
install: 
script: 
  - python FooFinder/test.py
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "deployment" ]]; then export RUN_DEPLOY="true"; fi
deploy:
  - provider: releases
    token: $RELEASES_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
      condition: $RUN_DEPLOY = "true"
    edge: true # opt in to dpl v2
  - provider: pypi
    distributions: sdist bdist_wheel
    username: "__token__"
    password: $PYPI_TOKEN
    on:
      tags: true
      condition: $RUN_DEPLOY = "true"
    edge: true # opt in to dpl v2
