# Copying from: https://github.com/brandtbucher/travis-python-matrix

matrix:
  include:
    - name: CPython nightly on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: nightly
    
    - name: CPython 3.8-dev on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.8-dev

    - name: CPython 3.8.0 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.8.0

    - name: CPython 3.7-dev on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7-dev
      
    - name: CPython 3.7.0 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7.0

    - name: CPython 3.6-dev on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.6-dev
      
    - name: CPython 3.6.1 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.6.1

    - name: CPython 3.5-dev on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.5-dev
      
    - name: CPython 3.5.2 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.5.2
    
    - name: CPython 3.8.5 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.5

    - name: CPython 3.8.0 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.0

    - name: CPython 3.7.9 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.9

    - name: CPython 3.7.0 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.0

    - name: CPython 3.6.8 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8

    - name: CPython 3.6.1 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.1

    - name: CPython 3.5.4 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.4.20200110
        
    - name: CPython 3.5.2 on Windows 10 (64-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.2.20161029
        
    - name: CPython 3.8.5 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.5 --x86

    - name: CPython 3.8.0 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - choco install python --version 3.8.0 --x86

    - name: CPython 3.7.9 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.9 --x86

    - name: CPython 3.7.0 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.0 --x86

    - name: CPython 3.6.8 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8 --x86

    - name: CPython 3.6.1 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.1 --x86

    - name: CPython 3.5.4 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.4.20200110 --x86
        
    - name: CPython 3.5.2 on Windows 10 (32-bit)
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.2.20161029 --x86
    
    - name: CPython 3.8-dev on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
    
    - name: CPython 3.8.0 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7-dev on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7.0 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.6-dev on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
        
    - name: CPython 3.6.1 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.1
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
        
    - name: CPython 3.5-dev on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5-dev
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

    - name: CPython 3.5.3 on macOS 10.15 (Catalina)
      language: shell
      os: osx
      osx_image: xcode12u
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.3
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
  
    - name: CPython 3.8-dev on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
    
    - name: CPython 3.8.0 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
    
    - name: CPython 3.7-dev on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.6-dev on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6-dev
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
    
    - name: CPython 3.6.1 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.1
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
    
    - name: CPython 3.5-dev on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5-dev
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
    
    - name: CPython 3.5.3 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode11.3
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.3
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

    - name: CPython 3.8-dev on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.8.0 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.8.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.7-dev on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
    
    - name: CPython 3.7.0 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.0
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
        
    - name: CPython 3.6-dev on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6-dev
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION

    - name: CPython 3.6.1 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.1
        - travis_wait brew upgrade pyenv && pyenv install $PYENV_VERSION
        
    - name: CPython 3.5-dev on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5-dev
        - pyenv install $PYENV_VERSION

    - name: CPython 3.5.2 on macOS 10.13 (High Sierra)
      language: shell
      os: osx
      osx_image: xcode10.1
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.2
        - pyenv install $PYENV_VERSION
    
    - stage: deployment
      language: python
      os: linux
      dist: xenial
      python: nightly
install: 
script: 
  - python FooFinder/test.py
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "deployment" ]]; then export RUN_DEPLOY="true"; fi
deploy:
  - provider: releases
    token: $RELEASES_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
      condition: $RUN_DEPLOY = "true"
    edge: true # opt in to dpl v2
  - provider: pypi
    distributions: sdist bdist_wheel
    username: "__token__"
    password: $PYPI_TOKEN
    on:
      tags: true
      condition: $RUN_DEPLOY = "true"
    edge: true # opt in to dpl v2
