# Copying from: https://github.com/brandtbucher/travis-python-matrix

matrix:
  include:
    - name: CPython 3.8.1 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.8.1

    - name: CPython 3.8.0 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.8.0

    - name: CPython 3.7.6 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7.6

    - name: CPython 3.7.5 on Ubuntu (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7.5
install: 
script: 
  - python FooFinder/test.py
  - if [[ "$TRAVIS_JOB_NUMBER" == *.4 ]]; then export RUN_DEPLOY="true"; fi
  - echo $PYPI_SECRET
  - echo $RELEASES_SECRET
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    username: "__token__"
    password: 
      secure: $PYPI_SECRET
    on:
      tags: true
      condition: $RUN_DEPLOY = "true"
    edge: true # opt in to dpl v2
  - provider: releases
    token: 
      secure: $RELEASES_SECRET
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
      condition: $RUN_DEPLOY = "true"
    edge: true # opt in to dpl v2