matrix:
  include:
    language: python
    python:
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.8-dev'
    - '3.9'
    - '3.9-dev'
    - 'nightly'
    install: 
    script:
    - python FooFinder/test.py
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    username: "__token__"
    password: 
      secure: "poUz1q0o9S2HbPfaE9+vOyjgP8nhBdqoUEFQwuvYCP2ztsMgfug0N/0rOkbdFckvpFk8m+v1z+9enRCGr92Ja+0xTf2ALBVWWR8RHiObH8fu/sPpYROGADssPSOCqhRlxJr/eunnJbKSj04NVU07Zu5QkPpIb+VpDS9TJLpu/qkPOrSx3+yA1C457PYH5gbgUw8Gx33A3WI+8CT9rTVLga04Ki/zzrObQDSHdEMD5ULz6fyVUMJdLOqnH1GCm3Thqm09F17Fh6+QqSYzbFFgugE6N/4LZ+fGtfMhqBLkr73kOR59T3K5TgCEGAFVhPCLXtJuB1gsF6lXtQl0k4WUNp4elLHzfHAKBZBZZtjeX1rp492wms9gdJ+bbN1qnbBlcQFjjcF0oJ7+ktftS+qZjg6yAsSajOOpAQvCAv4vz1wDjJDZhj1RjSIVCg/5AbWXjgawwn9Yk3/3y6IaD8vPw4CFmreL6SPdVMpkyLyp2/Hvqd5onaLRvvtZW/hS+pQzfbNcWGZZmjFWqsD4+ohiQ5Ql/CO3Fi6uxrWDEzDMps5aFwgn3xsBiGW7bM9xnbjuxIXy1djI+Y1TnDFU45uAglTcGQ+/0HqSAuZJ5GwT3vZQdfRLoIu8FeRvAnWIHGMyvSdupkYq4fpUxoF1W9dwTvAzjjapZvr8waEXfNsril8="
    on:
      tags: true
    edge: true # opt in to dpl v2
  - provider: releases
    token: 
      secure: "kNZyaq3FvikkQZZWqpRtYMQdhicq36ZJXDfZO1tKpZlGluEiQtfpzh0RICvNxuVEIeuDFKzYYjcWiaAs1H6gEyGe/Lgg9Zv8EEcGlSuv1YexVDkE67c1AQoMaNGG+L3cXqtWlUaIgq6CORmbRaIvYF39oTei4bvaN5v41OK4w18k5HyHedzB0r5yV9FNZaxNRdAdceZul/jZhWSOgwnQPnCKUlMAW5MzLB8uIeoJBsU3lnKfvpuEDXwA1FOPTnI6bcpDJViEYlPo438KnN/dmTZ4uxWRMADnjfzb5SEEHOONdt/oSXh0PGSZoM0al82HIjj1CqZ/Q0dQjej2VjfjhLcTjz+0jNHX2kzsitv8vCNnatGWbLZaRHlC6TjYQxLK2q55in8kCzYK8216x/yp2YduZu4pXB4o9oQbXnnIrQZS0pZatKHz0/UKPjWp4BwNGLj2LF2vsP40Mkq8rjhSC0iTTrsIjTxYTnOW02cGD+ATi3ZIHK+KAryR1xHEmhH8EqeM4pIdmyXTTP6oBgLkFcy1o4L5ZspkGSi5uQRsWFxinTK35gEv5WHVUYjwnP1OygzJrADb/irv6DCDgCA3dcZ+oN2C3SRFqRguHS6QKLU5OZBwTGdmDNV8DK/ThKZfN7MnrCc5cTEaFMm6oibABaZCLIa8/NjKsct26OskXsg="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
    edge: true # opt in to dpl v2