trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
stages:
- stage: Test
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        #Python27:
        #  python.version: '2.7'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    #- script: |
    #  displayName: 'Install dependencies'

    - script: |
        python FooFinder/test.py
      displayName: 'Integration Tests'

- stage: Deploy
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  dependsOn: Test
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - script: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel    
        python setup.py sdist
        python setup.py bdist_wheel --universal
      displayName: 'Build'

    - task: GithubRelease@0 
      displayName: 'Create GitHub Release'      
      inputs:
        gitHubConnection: FooFinder Release connection
        repositoryName: MadisonAster/FooFinder           
        assets: dist/*

    - task: TwineAuthenticate@1
      displayName: 'Twine Authenticate'
      inputs:
        # In this case, name of the service connection is "pypitest".
        pythonUploadServiceConnection: pypiservice
      
    # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
    - script: |
         python -m twine upload -r "pypiservice" --config-file $(PYPIRC_PATH) dist/*.whl
