trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
stages:
- stage: Test
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        #Python27:
        #  python.version: '2.7'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    #- script: |
    #  displayName: 'Install dependencies'

    - script: |
        python FooFinder/test.py
      displayName: 'Integration Tests'

- stage: Deploy
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  dependsOn: Test
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - script: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel    
        python setup.py sdist
        python setup.py bdist_wheel --universal
      displayName: 'Build'

    - task: GithubRelease@0 
      displayName: 'Create GitHub Release'      
      inputs:
        gitHubConnection: FooFinder Release connection
        repositoryName: MadisonAster/FooFinder           
        assets: dist/*

#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'artifact'
#      targetPath: 'dist'
#    displayName: 'Artifact Deployment'

