trigger:
- master
- azuretest

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    #Python27:
    #  python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

#- script: |
#  displayName: 'Install dependencies'

- script: |
    python FooFinder/test.py
  displayName: 'FooFinder/test.py'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade setuptools wheel    
  displayName: 'Install dependencies'

- script: |
        python setup.py sdist
  displayName: 'Make sdist'

- script: |
        python setup.py bdist_wheel --universal
  displayName: 'Make wheel'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'artifact'
    targetPath: 'dist'